---
title: "cross_val"
author: "Lizbeth Gomez"
date: "11/12/2019"
output: html_document
---
Lecture slides [here](https://p8105.com/cross_validation.html)
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)
library(mgcv)
```

Cross validation 
# generate datasert
```{r}

nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point() 
```


training and testing
```{r}
train_df = sample_frac(nonlin_df, .8)
test_df = anti_join(nonlin_df, train_df, by = "id") # whatever is not in 

ggplot(train_df, aes(x = x, y = y)) + 
  geom_point() + 
  geom_point(data = test_df, color = "red")
```

fit three models

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

```{r}
train_df %>% 
  add_predictions(linear_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_point(aes(y = pred), color = "red")
```

```{r}
train_df %>% 
  add_predictions(smooth_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
```

```{r}
train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
```

cross validation - make predictions that 
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df) # always pick the model that does better on the testing dataset
rmse(wiggly_mod, test_df)
```

