---
title: "Linear Models"
author: "Lizbeth Gomez"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Class slides [here](https://p8105.com/linear_models.html)

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```


lin model
```{r}
fit = lm (price ~ stars +boro, data = nyc_airbnb) # if you dont set a referene or dummy it'll take the alphabetical order

```

```{r, eval=FALSE}
fit
summary(fit)
coef(fit)
```

```{r}

fit %>% 
   broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro:")) %>% 
  knitr::kable(digits = 3)

fit %>% 
  broom::glance()
```

## take a look ar factors

%>
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro), 
    room_type = fct_infreq(room_type)
  )
```

refit the last nmodel

```{r}
fit = lm(price ~ stars +boro, data = nyc_airbnb)

fit %>% 
  broom::tidy()
```

## Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x=boro, y = resid)) + 
  geom_violin() + ylim (-500, 500)

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point() + 
  ylim (-500, 500)

modelr::add_predictions(nyc_airbnb, fit)

```

## Nesting

```{r}
fit_interaction = lm(price ~ stars * boro, data = nyc_airbnb) 

fit_interaction %>% 
  broom::tidy() 

fit_interaction = lm(price ~ stars * boro + room_type * boro, data = nyc_airbnb) 

fit_interaction %>% 
  broom::tidy()
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>% 
  lm( price ~ stars + room_type, data = .) %>% 
  broom::tidy()
```

mapping
```{r}
nyc_airbnb %>% 
  nest (data = -boro) %>% 
  mutate(
   models =  map(.x = data, ~ lm (price ~ stars +room_type, data = .x)), 
    results = map(models, broom::tidy)
  ) %>% 
  select(boro, results) %>% 
  unnest(results)
```

